### ISSUE TITLE
Running tests in docker image from Windows host shows "Operation not permitted" error

### ISSUE THREAD

**Issue by Mnuzz** [Bit-Nation/BITNATION-Pangea-libs#57]
Many tests show this error. Here is one example, when running in the docker image from a Windows host:
```
● profile › hasProfile › false

    expect(received).resolves.toBeFalsy()

    Expected received Promise to resolve, instead it rejected to value
      [Error: Operation not permitted]

      at Object.<anonymous> (node_modules/expect/build/index.js:131:11)
          at Generator.throw (<anonymous>)
      at step (node_modules/expect/build/index.js:40:727)
      at node_modules/expect/build/index.js:40:926
          at <anonymous>
      at runMicrotasksCallback (internal/process/next_tick.js:121:5)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Mnuzz** [comment]
Docker bug (ugh!): https://github.com/docker/for-win/issues/497
Possible workarounds: https://github.com/wodby/docker4drupal/issues/29

**Comment by Mnuzz** [comment]
My thinking is that the host's drive should not need to contain any temporary files. It should be code only. The docker image can write to its own virtualized disk, where it will have full permissions. The workarounds link has some ideas for how this can be done.

**Comment by florianlenz** [comment]
What's about to just write it to the `/tmp/` path in the docker container?

**Comment by Mnuzz** [comment]
I'm thinking that approach would technically fix this issue, but do mobile devices always allow access to that path? Changing the write path string *could* cause unknown issues somehow, as the database path would change in production as well?

Normally I'd just say try it anyway and get it over with but I would try one alternate approach first. The docker compose file could specify a mount point. The /app/database path could be set to point to /tmp/database. Behavior remains the same in production so nothing would break.

Neither approach is perfect but it's the one I'd try first just to guarantee that no new bugs are introduced.

**Comment by florianlenz** [comment]
The path is passed in dynamically: https://github.com/Bit-Nation/BITNATION-Pangea-libs/blob/develop/src/database/db.js#L31 we use a different one on production use :) But we can use your approche as well - makes more sense.

**Comment by florianlenz** [comment]
And It would actually be way faster since we keep tmp file's and test data in the machine and don't need to write them to the host. I definitely prefer your solution @Mnuzz feel free to implement it :)

**Comment by Mnuzz** [comment]
This is code-complete. Will include it in a later PR.
