### ISSUE TITLE
[tx] Processor don't process upcoming transactions.

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-libs#68]
## Problem / Task
The issue is that transactions processor only process transactions that are already exist. There is no way to start processing on new transactions, because of [this](https://github.com/Bit-Nation/BITNATION-Pangea-libs/blob/develop/src/queues/transaction.js#L248) flag that is never set back to false. 

## Expected Output
Worker to be called automatically after some time to process new transactions and/or _startWorker flag to be set back to false once worker is stopped.

## Reproduce
Call startProcessing()
Add new transaction by calling joinNation for example.
Calling startProcessing() won't start processing of new transaction and it won't happen automatically.

**Comment by florianlenz** [comment]
Actually it was designed to work like that (with the flag) but it assumed that new job's are added with the `addJob` method which put them on the processing stack. And every x seconds we restart the processor: https://github.com/Bit-Nation/BITNATION-Pangea-libs/blob/develop/src/queues/transaction.js#L277 But the new job's are not added via the add method. So I am gonna fix that :)
